services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: openfeed
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "${REDIS_DB_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8080
      HOSTNAME: "0.0.0.0"
      BETTER_AUTH_URL: http://localhost:8080
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}

      # POSTGRES
      DRIZZLE_DATABASE_URL: postgres://postgres:root@postgres:5432/openfeed

      # Google Auth 
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      # Github Auth
      AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
      AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
      
      # REDIS
      REDIS_URL: redis://redis:6379

      # Open Ai
      OPENAI_KEY: ${OPENAI_KEY}
      OPENAI_ENDPOINT: ${OPENAI_ENDPOINT}
      OPENAI_AGENT_MODEL: ${OPENAI_AGENT_MODEL}

      # email 
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_EMAIL: ${RESEND_EMAIL}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
volumes:
  postgres_data:
  redis_data:
