import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import { Geist_Mono, Nunito, Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-nunito",
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${nunito.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main
            className="relative flex min-h-screen"
          >
            <div className="absolute inset-0 overflow-hidden pointer-events-none">
              <div className="absolute -left-4 top-1/4 h-72 w-72 animate-blob rounded-full bg-teal-200/30 mix-blend-multiply blur-xl filter dark:bg-teal-900/20" />
              <div className="absolute -right-4 top-1/3 h-72 w-72 animate-blob animation-delay-2000 rounded-full bg-cyan-200/30 mix-blend-multiply blur-xl filter dark:bg-cyan-900/20" />
              <div className="absolute bottom-1/4 left-20 h-72 w-72 animate-blob animation-delay-4000 rounded-full bg-emerald-200/30 mix-blend-multiply blur-xl filter dark:bg-emerald-900/20" />
            </div>
            {children}
          </main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
